# Generated by Django 5.1.3 on 2026-08-03 09:52

import re

import django.db.models.deletion
from django.db import migrations, models


def bonus_code(raw):
    """Rebuild the Bonus.code that a redeemed UserSumma.code came from.

    CheckCodeView stores the code the user typed while Bonus.code holds the transformed
    one, so the two cannot be joined directly.
    """
    tail = re.search(r"(\d{4})(\D*$)", raw)
    if tail is None:
        return None
    stripped = raw.replace(tail.group(0), "")
    letter = re.search(r"([A-Z]$)", stripped)
    if letter is None:
        return None
    stripped = stripped[::-1].replace(letter.group(0), "", 1)[::-1]
    return f"{stripped}A0000{tail.group(2)}"


def backfill_points(apps, schema_editor):
    UserSumma = apps.get_model('product', 'UserSumma')
    Bonus = apps.get_model('product', 'Bonus')
    for point in UserSumma.objects.all().iterator():
        code = bonus_code(point.code)
        bonus = Bonus.objects.filter(code=code).first() if code else None
        point.bonus = bonus
        point.summa = bonus.summa if bonus else 0
        # Grandfather every existing redemption: expiry has never actually run, so
        # leaving these open would deduct a year of backlog from every balance on the
        # first nightly pass after this deploys.
        point.is_expired = True
        point.save(update_fields=['bonus', 'summa', 'is_expired'])


def dedupe_carts(apps, schema_editor):
    """Collapse the duplicate rows the old Cart.objects.create() left behind, keeping the
    newest per (user, product) — which is what the current upsert would hold."""
    Cart = apps.get_model('product', 'Cart')
    keep = {}
    drop = []
    for cart_id, user_id, product_id in (Cart.objects.order_by('id')
                                         .values_list('id', 'user_id', 'product_id')):
        key = (user_id, product_id)
        if key in keep:
            drop.append(keep[key])
        keep[key] = cart_id
    Cart.objects.filter(id__in=drop).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_is_completed'),
        ('user', '0004_notification_notificationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersumma',
            name='bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='product.bonus', verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='usersumma',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Истёк'),
        ),
        migrations.AddField(
            model_name='usersumma',
            name='summa',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.RunPython(backfill_points, migrations.RunPython.noop),
        # Must run before AlterUniqueTogether — the constraint cannot be added while
        # duplicate rows still exist.
        migrations.RunPython(dedupe_carts, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
