# Generated by Django 5.1.3 on 2026-08-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_verifyphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sent', 'Отправлено')], default='draft', max_length=10, verbose_name='Статус')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Доставлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Не доставлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданный на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='notifications/', verbose_name='Изображение')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.notification')),
            ],
        ),
    ]
