# Generated by Django 5.1.3 on 2026-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification_notificationimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='notificationimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
